package com.sandy.blog.greendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sandy.blog.greendaodemo.dao.Singer;

import com.sandy.blog.greendaodemo.dao.SingerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig singerDaoConfig;

    private final SingerDao singerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        singerDaoConfig = daoConfigMap.get(SingerDao.class).clone();
        singerDaoConfig.initIdentityScope(type);

        singerDao = new SingerDao(singerDaoConfig, this);

        registerDao(Singer.class, singerDao);
    }
    
    public void clear() {
        singerDaoConfig.clearIdentityScope();
    }

    public SingerDao getSingerDao() {
        return singerDao;
    }

}
